name: Build documentation

on:
  # NOMERGE
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Trigger docs build
        run: ./scripts/travis_update_docs.sh
        env:
          TRAVIS_BRANCH: maint_2_8
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
