---
name: Build packages

on:
  push:


jobs:
  build-macos:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
      - name: Checkout repos
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build packages
        run: ./scripts/build/build_macos.sh
        env:
          PACKAGE_NAME: psycopg2-binary
          PSYCOPG2_TESTDB: postgres
          PSYCOPG2_TEST_FAST: 1

      - name: test pg_config
        run: pg_config

      - name: test platform
        run: python -c "import sys; print(sys.platform)"
